import{a as f,S as y,i as a}from"./assets/vendor-BNibzuFn.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const h="https://pixabay.com/api/",b="52538556-e7ad6b62877d90490937495df";async function L(s){const o={key:b,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:50};try{return(await f.get(h,{params:o})).data}catch(r){throw r}}const d=document.getElementById("gallery"),c=document.getElementById("loader"),w=new y(".gallery a",{captionsData:"alt",captionDelay:250});function v(s){if(!Array.isArray(s)||s.length===0)return;const o=s.map(r=>{const{webformatURL:n,largeImageURL:e,tags:t,likes:i,views:g,comments:p,downloads:m}=r;return`
        <a class="photo-card-link" href="${e}">
          <div class="photo-card">
            <img src="${n}" alt="${t}" loading="lazy" />
            <div class="info">
              <p><b>Likes</b><br>${i}</p>
              <p><b>Views</b><br>${g}</p>
              <p><b>Comments</b><br>${p}</p>
              <p><b>Downloads</b><br>${m}</p>
            </div>
          </div>
        </a>
      `}).join("");d.insertAdjacentHTML("beforeend",o),w.refresh()}function E(){d.innerHTML=""}function I(){c&&c.classList.add("is-loading")}function l(){c&&c.classList.remove("is-loading")}const u=document.getElementById("search-form"),A=u.querySelector('input[name="search-text"]'),P=document.getElementById("gallery");u.addEventListener("submit",async s=>{s.preventDefault();const o=A.value.trim();if(!o){a.warning({title:"Warning",message:"Please enter a search query.",position:"topRight"});return}E(),I();try{const r=await L(o),n=Array.isArray(r.hits)?r.hits:[];if(n.length===0){a.error({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),l();return}v(n),a.success({title:"Success",message:`Found ${r.totalHits} images.`,position:"topRight"}),P.scrollIntoView({behavior:"smooth",block:"start"})}catch(r){console.error("Error fetching images:",r),a.error({title:"Error",message:"Something went wrong while fetching images. Please try again later.",position:"topRight"})}finally{l()}});
//# sourceMappingURL=index.js.map
